### ISSUE TITLE
Numeric identifier MUST NOT contain leading zeroes

### ISSUE THREAD

**Issue by kbytesys** [oharaandrew314/TinkerTime#233] opened 2015-05-11 12:30 UTC
I'm unable to install this module

https://kerbalstuff.com/mod/172

The zip file have leading zeroes in the name, btw you have manage that.

Regards

**Comment by Krahazik** [comment] 2015-05-25 02:05
I have encountered this error with other mods as well.
At the moment every time I start the program I get that error message and I'm not sure which mod its having a problem with.

**Comment by oharaandrew314** [comment] 2015-05-25 02:32
Duplicate of #221.  Was already fixed, but pending release.  See https://github.com/oharaandrew314/TinkerTime/releases/tag/v1.4.1

**Closed by oharaandrew314** 2015-05-25 02:32 UTC
