### ISSUE TITLE
Various exceptions reported from both curse and github updates.

### ISSUE THREAD

**Issue by cgruber** [oharaandrew314/TinkerTime#187] opened 2015-03-15 20:39 UTC
Note sure what's going on, but the scraping and/or github-api stuff is just not panning out with bob palmer's MKS.  There clearly are releases on the releases page, but nothing showsup.  I wonder if the scraping is falling afoul of the fact that bob lists pre-releases, and possibly the scraping is too brittle to notice those, and present them as releases. (I admit, I haven't dug in too deeply yet - quite busy)

**Comment by apemanzilla** [comment] 2015-03-15 20:41
The scraper does ignore pre-releases right now, but it should still find the release. It may be a problem where the latest tag is a pre-release and the latest release doesn't have the appropriate class the scraper is looking for.

**Comment by oharaandrew314** [comment] 2015-03-15 20:42
The API scraper seems to be downloading the pre-release version for me.

**Comment by cgruber** [comment] 2015-03-15 20:49
1.1.1

**Comment by cgruber** [comment] 2015-03-15 20:50
I can build master and try that, if you want.  I haven't peeked at the recent commits post 1.1.1, if you think those fix it.

**Comment by oharaandrew314** [comment] 2015-03-15 20:52
1.1.1 is still using the html scraping.  The commits past that point should reproduce the behaviour that I described, which is still an error, but not as severe.

**Comment by cgruber** [comment] 2015-03-15 21:12
I'll give it a shot.

**Comment by cgruber** [comment] 2015-03-15 21:31
Hmm.  MKS seemed to be recognized, but now I'm getting (for instance):

FileNotFoundException: https://api.github.com/repos/ferram4/Ferram-Aerospace-Research//releases

I think the extra slash is borking the query.

Also, I'm getting UnknownHostException for auth.curse.com

:/

**Comment by cgruber** [comment] 2015-03-15 21:31
Since I've just built from head - I'll debug this myself unless you have a solid idea how to fix and just want to roll it.

**Comment by oharaandrew314** [comment] 2015-03-15 21:34
@cgruber,

How are you getting this UnknownHostexception?  What url are you entering into TinkerTime?  TinkerTime does not support crawling url's from that domain.

TinkerTime does not support adding mods from the Github API url.  You still need to use the html url.

**Comment by cgruber** [comment] 2015-03-15 21:40
I have no idea what's going on with curse.  I certainly haven't ever entered a url like that - the UI rejects such anyway..  I wonder if curse is doing a re-direction to auth as a part of some normal login flow. 

As to github api - i didn't add anything from the api url.  These were plugins I had already installed the normal way, ... oh.. crap.  I wonder if I contaminated my own local data with my earlier experiment with github apis, so while I didn't enter a github api URL, it may have saved the URL.  I have to go look at that change again.  It seems to be handling things fine if I delete and re-download the given items.

Hmm.

**Comment by oharaandrew314** [comment] 2015-03-16 03:50
@cgruber, the issues you were having with the 1.1.1 Github Crawler were due to a site update.  I have reverted the crawler back to an html scraper, and updated the scraper on the [crawler-fixes](https://github.com/oharaandrew314/TinkerTime/tree/crawler-fixes) branch.

**Comment by oharaandrew314** [comment] 2015-03-16 04:08
@cgruber, can you try to reproduce your issues using the latest master?  If you can no longer reproduce, please close this issue.

**Comment by oharaandrew314** [comment] 2015-03-16 16:17
@cgruber, based on your comments in the V1.2 PR #189, I am closing this issue.

**Comment by oharaandrew314** [comment] 2015-03-16 16:20
Error when adding: https://github.com/ClawKSP/KSP-Stock-Bug-Fix-Modules.  No releases found.

**Comment by oharaandrew314** [comment] 2015-03-16 16:21
@cgruber, the issue here is that the "latest release" does not have a compiled version uploaded.  The crawler is specifically looking for the "latest release" div, so that "pre-releases" are avoided.

**Comment by cgruber** [comment] 2015-03-16 16:26
Ah - makes sense.

**Comment by apemanzilla** [comment] 2015-03-16 20:08
I figured it out. The crawler searches for the latest "release" tag (In the case of [this](https://github.com/ClawKSP/KSP-Stock-Bug-Fix-Modules/releases) mod, 0.1.7e) and after finding it, searches for compiled assets. Notice that the latest release for the mod linked above had the compiled download removed and only has assets for the source downloads - leading Tinker Time to find no assets for the latest release, throwing an error.

**Comment by oharaandrew314** [comment] 2015-03-16 20:09
Yep, exactly.

**Comment by cgruber** [comment] 2015-03-19 00:02
Verified.

**Closed** 2015-04-03 01:35 UTC
Labels: bug
