### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Tommassino** [oharaandrew314/TinkerTime#274] opened 2015-09-05 20:20 UTC
After starting TinkerTime uses about 200 MB of memory, but over time it steadily increases up to 2 GB within a few minutes and more.
I have 20 mods downloaded, but not activated, for a list of mods info see attached img.
![mods](https://cloud.githubusercontent.com/assets/698950/9701112/18ee9b6a-541c-11e5-966d-fea1e31f9775.png)

**Comment by oharaandrew314** [comment] 2015-09-20 20:40
Duplicate of #249

**Closed by oharaandrew314** 2015-09-20 20:40 UTC
